version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing-cloud
    hostname: remote-cloud
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - syncthing-config:/var/syncthing/config
      - syncthing-share:/var/syncthing
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      #- 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.syncthing-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.syncthing-https.entrypoints=https
        - traefik.http.routers.syncthing-https.tls=true
        - traefik.http.routers.syncthing-https.tls.certresolver=le
        - traefik.http.services.syncthing.loadbalancer.server.port=8384

volumes:
   syncthing-config:
   syncthing-share:

networks:
  traefik-public:
    external: true
